# -*- coding: utf-8 -*-
"""Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRSETbOld6YbEV5VKOb9XmnyKlicGW6M
"""

import pandas as pd
link = "https://github.com/Roshrol/Rpg-Class/blob/main/Oblivion/scrape_test.py" #our playwrite info should go here I believe
import io
import requests
csv_text = requests.get(link).text
# if you don't care about column names omit names=names and do headers=None instead
df = pd.read_csv(io.StringIO(csv_text), names=names)

df.head()

import torch
import pandas as pd
import pickle
import numpy as np

class DataPrepPipeline:
  def __init__(self):
    self.feature_cols = ["Strength", "Intelligence", "Willpower", "Agility", "Speed", "Endurance", "Personality", "Luck"]
    self.mean = None
    self.std = None
    self.class_type = {}

  def fit(self, X_df, y_df):
      self.mean = X_df[self.feature_cols].mean()
      self.std = X_df[self.feature_cols].std()

      classes = y_df.unique()
      for i, c in enumerate(classes):
          self.class_to_idx[c] = i

  def transform(self, X_df):
      X = (X_df[self.feature_cols] - self.mean) / (self.std + 1e-8)
      return torch.tensor(X.values, dtype=torch.float32)

  def transform_labels(self, y_df):
      y = [self.class_to_idx[c] for c in y_df]
      return torch.tensor(y, dtype=torch.long)

  def cross_entropy_loss(Q, y):
      Q = torch.clamp(Q, min=1e-7)
      return -torch.mean(y * torch.log(Q))

#multiclass logistic regression I think
class RPG_Model:
    def __init__(self, input_dim, num_classes):
      #our weights should be features x classes I think
      self.W = torch.randn(input_dim, num_classes, grad=True) #grad as in will need to be applied to the gradient
      self.b = torch.zeros(num_classes, grad=True)

    def forward(self, X):
      return X @ self.W + self.b

    def predict(self, X):
      Q = self.forward(X)
      return torch.argmax(Q, dim=1)


class GradientDescentOptimizer:
    def __init__(self, model, lr = 0.1):
        self.model = model
        self.lr = lr

    def step(self):
        self.model.W.data -= self.lr * self.model.W.grad
        self.model.b.data -= self.lr * self.model.b.grad

        self.model.W.grad.zero_()
        self.model.b.grad.zero_()

def train(model, opt, X, y, epochs=200):
  for epoch in range(epochs):
    Q = model.forward(X)
    loss = cross_entropy_loss(Q, y)
    loss.backward()
    opt.step()

    if epoch % 20 == 0:
      print(f"Epoch {epoch}, Loss: {loss.item()}")

def accuracy(model, X, y):
  pred = model.predict(X)
  return (pred == y).float().mean()

#Main function goes below

if __name__ == "__main__":
    # Load the data
    url = "https://github.com/Roshrol/Rpg-Class/blob/main/Oblivion/scrape_test.py"
    train = pd.read_csv(url)
    print(train.columns)

    # separate the features and targets
    X_df = train.drop(columns=["class"])
    y_df = train["class"]

    # fit and save the data prep pipeline
    pipeline = DataPrepPipeline()
    pipeline.fit(X_df, y_df)

    X = pipeline.transform(X_df)
    y = pipeline.transform_labels(y_df)

    # now we can apply the pipeline to the data to get it ready for training the model
    X_train = pipeline.transform(X_df)

    # train the model
    # taken/based from notebook
    y_train_df = pd.get_dummies(train["genre"])
    y_train = torch.tensor(y_train_df.values, dtype=torch.float32)

    model = GenreModel(X_train.shape[1], y_train.shape[1])
    opt = GradientDescentOptimizer(model, lr=0.1)

    losses = []
    for epoch in range(1000):
        q = model.forward(X_train)
        loss = cross_entropy(q, y_train)
        losses.append(loss.item())
        opt.step(X_train, y_train)

    # save the model
    with open("model.pkl", "wb") as f:
        pickle.dump(model, f)

    q = model.forward(X_train)
    print("Train loss:", cross_entropy(q, y_train).item())
    print("Train accuracy:", accuracy(q, y_train))