{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "machine_shape": "hm",
      "gpuType": "T4",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Roshrol/Rpg-Class/blob/main/Final_Project.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 16,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 290
        },
        "id": "IBAYLzsGBuI6",
        "outputId": "29777643-c399-434c-b763-6185aa40127c",
        "collapsed": true
      },
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "                                       url       class  Armorer  Athletics  \\\n",
              "0   https://www.elderstats.com/character/8       Thief      100         84   \n",
              "1  https://www.elderstats.com/character/22     Warrior       77         43   \n",
              "2  https://www.elderstats.com/character/31       Rogue       34          0   \n",
              "3  https://www.elderstats.com/character/38  Battlemage       22         40   \n",
              "4  https://www.elderstats.com/character/39     Warrior        0          0   \n",
              "\n",
              "   Blade  Block  Blunt  Hand to Hand  Heavy Armor  Alchemy  ...  Sneak  \\\n",
              "0    102     50     25            53          100       20  ...    102   \n",
              "1     59     48     32            35          100      100  ...     14   \n",
              "2     30     29      0             0            0        0  ...     54   \n",
              "3    100     19     16             5            9       41  ...     89   \n",
              "4    100      0      0             0            0        0  ...      0   \n",
              "\n",
              "   Speechcraft  Strength  Intelligence  Willpower  Agility  Speed  Endurance  \\\n",
              "0           80       100           100        100      100    100        100   \n",
              "1           19       100           100        100      100    100        100   \n",
              "2            0        56            56         56       56     56         56   \n",
              "3           11       102           102        102      102    102        102   \n",
              "4            0       100           100        100      100    100        100   \n",
              "\n",
              "   Personality  Luck  \n",
              "0          100   100  \n",
              "1          100   100  \n",
              "2           56    56  \n",
              "3          102   102  \n",
              "4          100   100  \n",
              "\n",
              "[5 rows x 31 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-a6d4761a-cfd0-4fe4-a640-c65a65f9d1e5\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>url</th>\n",
              "      <th>class</th>\n",
              "      <th>Armorer</th>\n",
              "      <th>Athletics</th>\n",
              "      <th>Blade</th>\n",
              "      <th>Block</th>\n",
              "      <th>Blunt</th>\n",
              "      <th>Hand to Hand</th>\n",
              "      <th>Heavy Armor</th>\n",
              "      <th>Alchemy</th>\n",
              "      <th>...</th>\n",
              "      <th>Sneak</th>\n",
              "      <th>Speechcraft</th>\n",
              "      <th>Strength</th>\n",
              "      <th>Intelligence</th>\n",
              "      <th>Willpower</th>\n",
              "      <th>Agility</th>\n",
              "      <th>Speed</th>\n",
              "      <th>Endurance</th>\n",
              "      <th>Personality</th>\n",
              "      <th>Luck</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>https://www.elderstats.com/character/8</td>\n",
              "      <td>Thief</td>\n",
              "      <td>100</td>\n",
              "      <td>84</td>\n",
              "      <td>102</td>\n",
              "      <td>50</td>\n",
              "      <td>25</td>\n",
              "      <td>53</td>\n",
              "      <td>100</td>\n",
              "      <td>20</td>\n",
              "      <td>...</td>\n",
              "      <td>102</td>\n",
              "      <td>80</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>https://www.elderstats.com/character/22</td>\n",
              "      <td>Warrior</td>\n",
              "      <td>77</td>\n",
              "      <td>43</td>\n",
              "      <td>59</td>\n",
              "      <td>48</td>\n",
              "      <td>32</td>\n",
              "      <td>35</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>...</td>\n",
              "      <td>14</td>\n",
              "      <td>19</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>https://www.elderstats.com/character/31</td>\n",
              "      <td>Rogue</td>\n",
              "      <td>34</td>\n",
              "      <td>0</td>\n",
              "      <td>30</td>\n",
              "      <td>29</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>...</td>\n",
              "      <td>54</td>\n",
              "      <td>0</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "      <td>56</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>https://www.elderstats.com/character/38</td>\n",
              "      <td>Battlemage</td>\n",
              "      <td>22</td>\n",
              "      <td>40</td>\n",
              "      <td>100</td>\n",
              "      <td>19</td>\n",
              "      <td>16</td>\n",
              "      <td>5</td>\n",
              "      <td>9</td>\n",
              "      <td>41</td>\n",
              "      <td>...</td>\n",
              "      <td>89</td>\n",
              "      <td>11</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "      <td>102</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>https://www.elderstats.com/character/39</td>\n",
              "      <td>Warrior</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>100</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>...</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5 rows × 31 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-a6d4761a-cfd0-4fe4-a640-c65a65f9d1e5')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-a6d4761a-cfd0-4fe4-a640-c65a65f9d1e5 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-a6d4761a-cfd0-4fe4-a640-c65a65f9d1e5');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "train"
            }
          },
          "metadata": {},
          "execution_count": 16
        }
      ],
      "source": [
        "import pandas as pd\n",
        "url = \"https://raw.githubusercontent.com/Roshrol/Rpg-Class/refs/heads/main/Oblivion/oblivion_characters_all.csv\" #our playwrite info should go here I believe\n",
        "train = pd.read_csv(url)\n",
        "train.head()\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import torch\n",
        "import pandas as pd\n",
        "import pickle\n",
        "import numpy as np\n",
        "\n",
        "class DataPrepPipeline:\n",
        "  def __init__(self):\n",
        "\n",
        "    self.feature_cols = [\"Strength\", \"Intelligence\", \"Willpower\", \"Agility\", \"Speed\",\n",
        "                         \"Endurance\", \"Personality\", \"Luck\",\n",
        "                         \"Armorer\",  \"Athletics\", \"Blade\", \"Block\", \"Blunt\", \"Hand to Hand\", \"Heavy Armor\",\n",
        "                         \"Alchemy\", \"Alteration\", \"Conjuration\", \"Destruction\", \"Illusion\", \"Mysticism\",\n",
        "                         \"Restoration\", \"Acrobatics\", \"Light Armor\", \"Marksman\", \"Mercantile\", \"Security\",\n",
        "                         \"Sneak\", \"Speechcraft\"]\n",
        "    self.mean = None\n",
        "    self.std = None\n",
        "    self.class_type = {}\n",
        "\n",
        "  def fit(self, X_df, y_df):\n",
        "    self.mean = X_df[self.feature_cols].mean()\n",
        "    self.std = X_df[self.feature_cols].std()\n",
        "\n",
        "    classes = y_df.unique()\n",
        "    for i, c in enumerate(classes):\n",
        "        self.class_type[c] = i\n",
        "\n",
        "  def transform(self, X_df):\n",
        "    X = (X_df[self.feature_cols] - self.mean) / (self.std + 1e-8)\n",
        "    return torch.tensor(X.values, dtype=torch.float32)\n",
        "\n",
        "  def transform_labels(self, y_df):\n",
        "    y = [self.class_type[c] for c in y_df]\n",
        "    return torch.tensor(y, dtype=torch.long) # made it long instead of a float\n",
        "\n",
        "def cross_entropy_loss(q, y):\n",
        "  return torch.nn.functional.cross_entropy(q, y) #need to check if this is allowed\n",
        "  #bc taken from stack overflow and uses py torch's multiclass cross entropy\n",
        "\n",
        "#multiclass logistic regression I think\n",
        "class RPG_Model:\n",
        "    def __init__(self, input_dim, num_classes):\n",
        "      #our weights should be features x classes I think\n",
        "      self.W = torch.randn(input_dim, num_classes, requires_grad=True) #grad as in will need to be applied to the gradient\n",
        "      self.b = torch.zeros(num_classes, requires_grad=True)\n",
        "\n",
        "    def forward(self, X):\n",
        "      return X @ self.W + self.b\n",
        "\n",
        "    def predict(self, X):\n",
        "      q = self.forward(X)\n",
        "      return torch.argmax(q, dim=1)\n",
        "\n",
        "\n",
        "class GradientDescentOptimizer:\n",
        "    def __init__(self, model, lr = 0.1):\n",
        "        self.model = model\n",
        "        self.lr = lr\n",
        "\n",
        "    def step(self):\n",
        "        self.model.W.data -= self.lr * self.model.W.grad\n",
        "        self.model.b.data -= self.lr * self.model.b.grad\n",
        "\n",
        "        self.model.W.grad.zero_()\n",
        "        self.model.b.grad.zero_()\n",
        "\n",
        "def accuracy(model, X, y):\n",
        "  pred = model.predict(X)\n",
        "  return (pred == y).float().mean()\n",
        "\n",
        "#Main function goes below\n",
        "#hi\n",
        "if __name__ == \"__main__\":\n",
        "    # Load the data\n",
        "    #url = \"https://raw.githubusercontent.com/Roshrol/Rpg-Class/refs/heads/main/Oblivion/oblivion_characters.csv\"\n",
        "    url = \"https://raw.githubusercontent.com/Roshrol/Rpg-Class/refs/heads/main/Oblivion/oblivion_characters_all.csv\"\n",
        "    train = pd.read_csv(url)\n",
        "    print(train.columns)\n",
        "\n",
        "    # separate the features and targets\n",
        "    X_df = train.drop(columns=[\"class\"])\n",
        "    y_df = train[\"class\"]\n",
        "\n",
        "    # fit and save the data prep pipeline\n",
        "    pipeline = DataPrepPipeline()\n",
        "    pipeline.fit(X_df, y_df)\n",
        "\n",
        "    X_train = pipeline.transform(X_df)\n",
        "    y_train = pipeline.transform_labels(y_df)\n",
        "\n",
        "\n",
        "    num_classes = len(set(y_df))\n",
        "    model = RPG_Model(X_train.shape[1], num_classes)\n",
        "    opt = GradientDescentOptimizer(model, lr=0.1)\n",
        "\n",
        "    losses = []\n",
        "\n",
        "    for epoch in range(50000):\n",
        "        q = model.forward(X_train)\n",
        "        loss = cross_entropy_loss(q, y_train)\n",
        "\n",
        "        loss.backward()\n",
        "        opt.step()\n",
        "\n",
        "        losses.append(loss.item())\n",
        "\n",
        "        if epoch % 1000 == 0:\n",
        "            print(f\"Epoch {epoch}, Loss: {loss.item()}\")\n",
        "            #print(f\"Epoch {epoch}, Accuracy: {acc.item()}\")\n",
        "\n",
        "\n",
        "    # save the model\n",
        "    with open(\"model.pkl\", \"wb\") as f:\n",
        "        pickle.dump(model, f)\n",
        "\n",
        "    q = model.forward(X_train)\n",
        "    final = cross_entropy_loss(q, y_train).item()\n",
        "    acc = accuracy(model, X_train, y_train).item()\n",
        "    print(\"Train loss:\", final)\n",
        "    print(\"Train accuracy:\", acc)"
      ],
      "metadata": {
        "id": "XuAdT-6pFfGX",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "b1cb1dae-defe-4a48-ec20-fef049e57f75"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Index(['url', 'class', 'Armorer', 'Athletics', 'Blade', 'Block', 'Blunt',\n",
            "       'Hand to Hand', 'Heavy Armor', 'Alchemy', 'Alteration', 'Conjuration',\n",
            "       'Destruction', 'Illusion', 'Mysticism', 'Restoration', 'Acrobatics',\n",
            "       'Light Armor', 'Marksman', 'Mercantile', 'Security', 'Sneak',\n",
            "       'Speechcraft', 'Strength', 'Intelligence', 'Willpower', 'Agility',\n",
            "       'Speed', 'Endurance', 'Personality', 'Luck'],\n",
            "      dtype='object')\n",
            "Epoch 0, Loss: 4.917974948883057\n",
            "Epoch 1000, Loss: 1.8802677392959595\n",
            "Epoch 2000, Loss: 1.6218034029006958\n",
            "Epoch 3000, Loss: 1.4891357421875\n",
            "Epoch 4000, Loss: 1.4069089889526367\n",
            "Epoch 5000, Loss: 1.3503257036209106\n",
            "Epoch 6000, Loss: 1.3088159561157227\n",
            "Epoch 7000, Loss: 1.2768319845199585\n",
            "Epoch 8000, Loss: 1.2512023448944092\n",
            "Epoch 9000, Loss: 1.2300254106521606\n",
            "Epoch 10000, Loss: 1.2121115922927856\n",
            "Epoch 11000, Loss: 1.196671962738037\n",
            "Epoch 12000, Loss: 1.183153510093689\n",
            "Epoch 13000, Loss: 1.171165108680725\n",
            "Epoch 14000, Loss: 1.1604231595993042\n",
            "Epoch 15000, Loss: 1.1507153511047363\n",
            "Epoch 16000, Loss: 1.1418776512145996\n",
            "Epoch 17000, Loss: 1.1337814331054688\n",
            "Epoch 18000, Loss: 1.1263234615325928\n",
            "Epoch 19000, Loss: 1.119420051574707\n",
            "Epoch 20000, Loss: 1.113003134727478\n",
            "Epoch 21000, Loss: 1.1070150136947632\n",
            "Epoch 22000, Loss: 1.1014084815979004\n",
            "Epoch 23000, Loss: 1.0961430072784424\n",
            "Epoch 24000, Loss: 1.0911842584609985\n",
            "Epoch 25000, Loss: 1.0865025520324707\n",
            "Epoch 26000, Loss: 1.082072377204895\n",
            "Epoch 27000, Loss: 1.0778714418411255\n",
            "Epoch 28000, Loss: 1.0738803148269653\n",
            "Epoch 29000, Loss: 1.0700817108154297\n",
            "Epoch 30000, Loss: 1.066460371017456\n",
            "Epoch 31000, Loss: 1.0630028247833252\n",
            "Epoch 32000, Loss: 1.0596970319747925\n",
            "Epoch 33000, Loss: 1.0565320253372192\n",
            "Epoch 34000, Loss: 1.0534982681274414\n",
            "Epoch 35000, Loss: 1.0505867004394531\n",
            "Epoch 36000, Loss: 1.047789454460144\n",
            "Epoch 37000, Loss: 1.0450993776321411\n",
            "Epoch 38000, Loss: 1.0425095558166504\n",
            "Epoch 39000, Loss: 1.0400141477584839\n",
            "Epoch 40000, Loss: 1.0376079082489014\n",
            "Epoch 41000, Loss: 1.0352848768234253\n",
            "Epoch 42000, Loss: 1.03304123878479\n",
            "Epoch 43000, Loss: 1.0308722257614136\n",
            "Epoch 44000, Loss: 1.0287737846374512\n",
            "Epoch 45000, Loss: 1.0267423391342163\n",
            "Epoch 46000, Loss: 1.0247746706008911\n",
            "Epoch 47000, Loss: 1.02286696434021\n",
            "Epoch 48000, Loss: 1.021017074584961\n",
            "Epoch 49000, Loss: 1.0192214250564575\n",
            "Train loss: 1.0174777507781982\n",
            "Train accuracy: 0.7057416439056396\n"
          ]
        }
      ]
    }
  ]
}