{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "machine_shape": "hm",
      "gpuType": "G4",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Roshrol/Rpg-Class/blob/main/Final_Project.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 29,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 224
        },
        "id": "IBAYLzsGBuI6",
        "outputId": "04d58e6f-6a65-48c3-ea38-06c7adfa6b5f",
        "collapsed": true
      },
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "                                       url        class  Strength  \\\n",
              "0   https://www.elderstats.com/character/8        Thief       100   \n",
              "1   https://www.elderstats.com/character/9      Acrobat       255   \n",
              "2  https://www.elderstats.com/character/11       Shadow       100   \n",
              "3  https://www.elderstats.com/character/20  Shadowscale        47   \n",
              "4  https://www.elderstats.com/character/21         Hero        75   \n",
              "\n",
              "   Intelligence  Willpower  Agility  Speed  Endurance  Personality  Luck  \n",
              "0            75         88      100    100         90           90    61  \n",
              "1           255        255      255    255        255          255   255  \n",
              "2            81         97      100     86        100           39    62  \n",
              "3            42         30       63     60         33           33    50  \n",
              "4            30         32       47     45         75           30    50  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-f37d5070-075d-4169-bcc4-41d647008080\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>url</th>\n",
              "      <th>class</th>\n",
              "      <th>Strength</th>\n",
              "      <th>Intelligence</th>\n",
              "      <th>Willpower</th>\n",
              "      <th>Agility</th>\n",
              "      <th>Speed</th>\n",
              "      <th>Endurance</th>\n",
              "      <th>Personality</th>\n",
              "      <th>Luck</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>https://www.elderstats.com/character/8</td>\n",
              "      <td>Thief</td>\n",
              "      <td>100</td>\n",
              "      <td>75</td>\n",
              "      <td>88</td>\n",
              "      <td>100</td>\n",
              "      <td>100</td>\n",
              "      <td>90</td>\n",
              "      <td>90</td>\n",
              "      <td>61</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>https://www.elderstats.com/character/9</td>\n",
              "      <td>Acrobat</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "      <td>255</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>https://www.elderstats.com/character/11</td>\n",
              "      <td>Shadow</td>\n",
              "      <td>100</td>\n",
              "      <td>81</td>\n",
              "      <td>97</td>\n",
              "      <td>100</td>\n",
              "      <td>86</td>\n",
              "      <td>100</td>\n",
              "      <td>39</td>\n",
              "      <td>62</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>https://www.elderstats.com/character/20</td>\n",
              "      <td>Shadowscale</td>\n",
              "      <td>47</td>\n",
              "      <td>42</td>\n",
              "      <td>30</td>\n",
              "      <td>63</td>\n",
              "      <td>60</td>\n",
              "      <td>33</td>\n",
              "      <td>33</td>\n",
              "      <td>50</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>https://www.elderstats.com/character/21</td>\n",
              "      <td>Hero</td>\n",
              "      <td>75</td>\n",
              "      <td>30</td>\n",
              "      <td>32</td>\n",
              "      <td>47</td>\n",
              "      <td>45</td>\n",
              "      <td>75</td>\n",
              "      <td>30</td>\n",
              "      <td>50</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-f37d5070-075d-4169-bcc4-41d647008080')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-f37d5070-075d-4169-bcc4-41d647008080 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-f37d5070-075d-4169-bcc4-41d647008080');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "train",
              "summary": "{\n  \"name\": \"train\",\n  \"rows\": 20,\n  \"fields\": [\n    {\n      \"column\": \"url\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 20,\n        \"samples\": [\n          \"https://www.elderstats.com/character/8\",\n          \"https://www.elderstats.com/character/38\",\n          \"https://www.elderstats.com/character/36\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"class\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 15,\n        \"samples\": [\n          \"Spartan\",\n          \"Wanderer\",\n          \"Thief\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Strength\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 61,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 9,\n        \"samples\": [\n          56,\n          255,\n          89\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Intelligence\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 59,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 11,\n        \"samples\": [\n          37,\n          75,\n          49\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Willpower\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 61,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          40,\n          255,\n          41\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Agility\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 60,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 11,\n        \"samples\": [\n          0,\n          100,\n          79\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Speed\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 61,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 11,\n        \"samples\": [\n          44,\n          100,\n          90\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Endurance\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 61,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          94,\n          255,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Personality\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 57,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 12,\n        \"samples\": [\n          82,\n          55,\n          90\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Luck\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 56,\n        \"min\": 0,\n        \"max\": 255,\n        \"num_unique_values\": 9,\n        \"samples\": [\n          60,\n          255,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 29
        }
      ],
      "source": [
        "import pandas as pd\n",
        "url = \"https://raw.githubusercontent.com/Roshrol/Rpg-Class/refs/heads/main/Oblivion/oblivion_characters.csv\" #our playwrite info should go here I believe\n",
        "train = pd.read_csv(url)\n",
        "train.head()\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import torch\n",
        "import pandas as pd\n",
        "import pickle\n",
        "import numpy as np\n",
        "\n",
        "class DataPrepPipeline:\n",
        "  def __init__(self):\n",
        "    self.feature_cols = [\"Strength\", \"Intelligence\", \"Willpower\", \"Agility\", \"Speed\", \"Endurance\", \"Personality\", \"Luck\"]\n",
        "    self.mean = None\n",
        "    self.std = None\n",
        "    self.class_type = {}\n",
        "\n",
        "  def fit(self, X_df, y_df):\n",
        "    self.mean = X_df[self.feature_cols].mean()\n",
        "    self.std = X_df[self.feature_cols].std()\n",
        "\n",
        "    classes = y_df.unique()\n",
        "    for i, c in enumerate(classes):\n",
        "        self.class_type[c] = i\n",
        "\n",
        "  def transform(self, X_df):\n",
        "    X = (X_df[self.feature_cols] - self.mean) / (self.std + 1e-8)\n",
        "    return torch.tensor(X.values, dtype=torch.float32)\n",
        "\n",
        "  def transform_labels(self, y_df):\n",
        "    y = [self.class_type[c] for c in y_df]\n",
        "    return torch.tensor(y, dtype=torch.float32)\n",
        "\n",
        "def cross_entropy_loss(q, y):\n",
        "  return -(y * torch.log(q + 1e-8)).sum(dim=1).mean()\n",
        "\n",
        "#multiclass logistic regression I think\n",
        "class RPG_Model:\n",
        "    def __init__(self, input_dim, num_classes):\n",
        "      #our weights should be features x classes I think\n",
        "      self.W = torch.randn(input_dim, num_classes, requires_grad=True) #grad as in will need to be applied to the gradient\n",
        "      self.b = torch.zeros(num_classes, requires_grad=True)\n",
        "\n",
        "    def forward(self, X):\n",
        "      return X @ self.W + self.b\n",
        "\n",
        "    def predict(self, X):\n",
        "      q = self.forward(X)\n",
        "      return torch.argmax(q, dim=1)\n",
        "\n",
        "\n",
        "class GradientDescentOptimizer:\n",
        "    def __init__(self, model, lr = 0.1):\n",
        "        self.model = model\n",
        "        self.lr = lr\n",
        "\n",
        "    def step(self):\n",
        "        self.model.W.data -= self.lr * self.model.W.grad\n",
        "        self.model.b.data -= self.lr * self.model.b.grad\n",
        "\n",
        "        self.model.W.grad.zero_()\n",
        "        self.model.b.grad.zero_()\n",
        "\n",
        "def accuracy(model, X, y):\n",
        "  pred = model.predict(X)\n",
        "  return (pred == y).float().mean()\n",
        "\n",
        "#Main function goes below\n",
        "#hi\n",
        "if __name__ == \"__main__\":\n",
        "    # Load the data\n",
        "    url = \"https://raw.githubusercontent.com/Roshrol/Rpg-Class/refs/heads/main/Oblivion/oblivion_characters.csv\"\n",
        "    train = pd.read_csv(url)\n",
        "    print(train.columns)\n",
        "\n",
        "    # separate the features and targets\n",
        "    X_df = train.drop(columns=[\"class\"])\n",
        "    y_df = train[\"class\"]\n",
        "\n",
        "    # fit and save the data prep pipeline\n",
        "    pipeline = DataPrepPipeline()\n",
        "    pipeline.fit(X_df, y_df)\n",
        "\n",
        "    X_train = pipeline.transform(X_df)\n",
        "    y_train = pipeline.transform_labels(y_df)\n",
        "\n",
        "\n",
        "    num_classes = len(set(y_df))\n",
        "    model = RPG_Model(X_train.shape[1], num_classes)\n",
        "    opt = GradientDescentOptimizer(model, lr=0.01)\n",
        "\n",
        "    losses = []\n",
        "\n",
        "    for epoch in range(200):\n",
        "        q = model.forward(X_train)\n",
        "        loss = cross_entropy_loss(q, y_train)\n",
        "\n",
        "        loss.backward()\n",
        "        opt.step()\n",
        "\n",
        "        losses.append(loss.item())\n",
        "\n",
        "        if epoch % 20 == 0:\n",
        "            print(f\"Epoch {epoch}, Loss: {loss.item()}\")\n",
        "\n",
        "\n",
        "    # save the model\n",
        "    with open(\"model.pkl\", \"wb\") as f:\n",
        "        pickle.dump(model, f)\n",
        "\n",
        "    q = model.forward(X_train)\n",
        "    final = cross_entropy_loss(q, y_train).item()\n",
        "    acc = accuracy(model, X_train, y_train).item()\n",
        "    print(\"Train loss:\", final)\n",
        "    print(\"Train accuracy:\", acc)"
      ],
      "metadata": {
        "id": "XuAdT-6pFfGX",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 394
        },
        "outputId": "67357d67-b25b-417f-dc22-fee3149c5878"
      },
      "execution_count": 28,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Index(['url', 'class', 'Strength', 'Intelligence', 'Willpower', 'Agility',\n",
            "       'Speed', 'Endurance', 'Personality', 'Luck'],\n",
            "      dtype='object')\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "RuntimeError",
          "evalue": "The size of tensor a (20) must match the size of tensor b (15) at non-singleton dimension 1",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_2631/3999103075.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     89\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mepoch\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m200\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     90\u001b[0m         \u001b[0mq\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mforward\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 91\u001b[0;31m         \u001b[0mloss\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcross_entropy_loss\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mq\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     92\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     93\u001b[0m         \u001b[0mloss\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbackward\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/tmp/ipykernel_2631/3999103075.py\u001b[0m in \u001b[0;36mcross_entropy_loss\u001b[0;34m(q, y)\u001b[0m\n\u001b[1;32m     28\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     29\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mcross_entropy_loss\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mq\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 30\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0;34m-\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0mtorch\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlog\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mq\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;36m1e-8\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdim\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmean\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     31\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     32\u001b[0m \u001b[0;31m#multiclass logistic regression I think\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mRuntimeError\u001b[0m: The size of tensor a (20) must match the size of tensor b (15) at non-singleton dimension 1"
          ]
        }
      ]
    }
  ]
}